### ISSUE TITLE
Extension writes empty lines to my file while idle. 

### ISSUE THREAD

**Issue by robjac** [spgennard/vscode_crosshair#1]
Not sure why, but when this extension is on, it starts to write spaces and empty lines to my file. I'm using vim mode inside of vscode and also have a max 80 character column. Linters and auto fixers only run on save, so I don't think this is the issue.

**Comment by spgennard** [comment]
Using the following settings will sort this issue and the extension will set these by default.

```json
            "editor.trimAutoWhitespace": true,
            "files.trimFinalNewlines": true,
            "files.trimTrailingWhitespace": true
```
